// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esetgrzlhuemtzqzzmaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZXRncnpsaHVlbXR6cXp6bWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDQxMzksImV4cCI6MjA2Mjc4MDEzOX0.nWqd5Xak-qXs02kKXXPhRtoyV_k62zi2CsQpWjrOUag";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
