// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxvioblkkzysnadunlvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4dmlvYmxra3p5c25hZHVubHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDIwNTEsImV4cCI6MjA2MjExODA1MX0.N9Dwnd_Nq76dBx_ESMysr7-LcTfDDUQiMx3gS5n-9CI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);